"""Initial Schema Complete

Revision ID: 324edd6a9c4c
Revises: 
Create Date: 2025-12-15 20:25:16.518440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324edd6a9c4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentes_responsaveis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo_taxonomia', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_taxonomia'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('descricao_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dotacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('codigo_dotacao', sa.String(length=100), nullable=False),
    sa.Column('numero_ficha', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('exercicio IS NOT NULL', name='check_exercicio_not_null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_necessidade', sa.Text(), nullable=True),
    sa.Column('previsao_pca', sa.Text(), nullable=True),
    sa.Column('requisitos_tecnicos', sa.Text(), nullable=True),
    sa.Column('motivacao_contratacao', sa.Text(), nullable=True),
    sa.Column('levantamento_mercado', sa.Text(), nullable=True),
    sa.Column('justificativa_escolha', sa.Text(), nullable=True),
    sa.Column('descricao_solucao', sa.Text(), nullable=True),
    sa.Column('estimativa_custos', sa.Text(), nullable=True),
    sa.Column('justificativa_parcelamento', sa.Text(), nullable=True),
    sa.Column('demonstrativo_resultados', sa.Text(), nullable=True),
    sa.Column('providencias_previas', sa.Text(), nullable=True),
    sa.Column('impactos_ambientais', sa.Text(), nullable=True),
    sa.Column('viabilidade', sa.Boolean(), nullable=True),
    sa.Column('conclusao_viabilidade', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('instrumentocontratual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('locais_entrega',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('modalidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('fundamentacao_legal', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidades_requisitantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('codigo_administrativo', sa.String(length=20), nullable=True),
    sa.Column('id_unidade_pai', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_unidade_pai'], ['unidades_requisitantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('v_saldo_itens_contrato',
    sa.Column('id_item_contrato', sa.Integer(), nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('nome_item', sa.String(), nullable=False),
    sa.Column('quantidade_contratada', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('total_consumido', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('saldo_disponivel', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id_item_contrato'),
    info={'is_view': True}
    )
    op.create_table('aocs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_aocs', sa.String(length=100), nullable=False),
    sa.Column('ano_aocs', sa.Integer(), nullable=False),
    sa.Column('numero_pedido_externo', sa.String(length=50), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('id_unidade_requisitante', sa.Integer(), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=True),
    sa.Column('id_agente_responsavel', sa.Integer(), nullable=True),
    sa.Column('id_local_entrega', sa.Integer(), nullable=True),
    sa.Column('id_dotacao', sa.Integer(), nullable=True),
    sa.Column('empenho', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_agente_responsavel'], ['agentes_responsaveis.id'], ),
    sa.ForeignKeyConstraint(['id_dotacao'], ['dotacao.id'], ),
    sa.ForeignKeyConstraint(['id_local_entrega'], ['locais_entrega.id'], ),
    sa.ForeignKeyConstraint(['id_solicitante'], ['agentes_responsaveis.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_requisitante'], ['unidades_requisitantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_aocs')
    )
    op.create_table('dfds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('numero_protocolo_string', sa.String(length=50), nullable=True),
    sa.Column('descricao_sucinta', sa.String(length=255), nullable=False),
    sa.Column('justificativa_necessidade', sa.Text(), nullable=True),
    sa.Column('unidade_requisitante_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['unidade_requisitante_id'], ['unidades_requisitantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dfds_numero_protocolo_string'), 'dfds', ['numero_protocolo_string'], unique=False)
    op.create_table('etp_dotacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etp_id', sa.Integer(), nullable=True),
    sa.Column('dotacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dotacao_id'], ['dotacao.id'], ),
    sa.ForeignKeyConstraint(['etp_id'], ['etps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etp_equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etp_id', sa.Integer(), nullable=True),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('papel', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes_responsaveis.id'], ),
    sa.ForeignKeyConstraint(['etp_id'], ['etps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.CHAR(length=2), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrizes_risco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etp_id'], ['etps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etp_id')
    )
    op.create_table('numeros_modalidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_modalidade', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_modalidade'], ['modalidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ci_pagamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aocs', sa.Integer(), nullable=False),
    sa.Column('numero_ci', sa.String(length=50), nullable=False),
    sa.Column('data_ci', sa.Date(), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=True),
    sa.Column('id_dotacao_pagamento', sa.Integer(), nullable=True),
    sa.Column('numero_nota_fiscal', sa.String(length=100), nullable=False),
    sa.Column('serie_nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('data_nota_fiscal', sa.Date(), nullable=False),
    sa.Column('valor_nota_fiscal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('codigo_acesso_nota', sa.String(length=44), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_aocs'], ['aocs.id'], ),
    sa.ForeignKeyConstraint(['id_dotacao_pagamento'], ['dotacao.id'], ),
    sa.ForeignKeyConstraint(['id_solicitante'], ['agentes_responsaveis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ci')
    )
    op.create_table('dfd_dotacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dfd_id', sa.Integer(), nullable=True),
    sa.Column('dotacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dfd_id'], ['dfds.id'], ),
    sa.ForeignKeyConstraint(['dotacao_id'], ['dotacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dfd_equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dfd_id', sa.Integer(), nullable=True),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('papel', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes_responsaveis.id'], ),
    sa.ForeignKeyConstraint(['dfd_id'], ['dfds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_risco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=True),
    sa.Column('descricao_risco', sa.Text(), nullable=True),
    sa.Column('probabilidade', sa.String(length=50), nullable=True),
    sa.Column('impacto', sa.String(length=50), nullable=True),
    sa.Column('medida_preventiva', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matriz_id'], ['matrizes_risco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('username_snapshot', sa.String(length=80), nullable=True),
    sa.Column('data_acao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('tabela_afetada', sa.String(length=100), nullable=False),
    sa.Column('id_registro_afetado', sa.Integer(), nullable=True),
    sa.Column('tipo_acao', sa.String(length=20), nullable=False),
    sa.Column('dados_antigos', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('descricao_legivel', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_item_contrato', sa.Integer(), nullable=False),
    sa.Column('id_aocs', sa.Integer(), nullable=False),
    sa.Column('quantidade_pedida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('status_entrega', sa.String(), nullable=False),
    sa.Column('quantidade_entregue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_aocs'], ['aocs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_dfd', sa.String(), nullable=False),
    sa.Column('secretaria', sa.String(), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('valor_estimado', sa.String(), nullable=False),
    sa.Column('valor_extenso', sa.String(), nullable=False),
    sa.Column('dotacao', sa.Text(), nullable=True),
    sa.Column('artigo', sa.String(), nullable=True),
    sa.Column('data1', sa.String(), nullable=True),
    sa.Column('data2', sa.String(), nullable=True),
    sa.Column('data3', sa.String(), nullable=True),
    sa.Column('data4', sa.String(), nullable=True),
    sa.Column('data5', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processos_licitatorios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dfd', sa.Integer(), nullable=False),
    sa.Column('numero_processo', sa.Integer(), nullable=False),
    sa.Column('ano_processo', sa.Integer(), nullable=False),
    sa.Column('id_modalidade', sa.Integer(), nullable=False),
    sa.Column('id_numero_modalidade', sa.Integer(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('valor_total_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_homologacao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_dfd'], ['dfds.id'], ),
    sa.ForeignKeyConstraint(['id_modalidade'], ['modalidade.id'], ),
    sa.ForeignKeyConstraint(['id_numero_modalidade'], ['numeros_modalidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subgrupos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.CHAR(length=2), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=True),
    sa.Column('fundamentacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matriz_id'], ['matrizes_risco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matriz_id')
    )
    op.create_table('catalogo_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subgrupo', sa.Integer(), nullable=False),
    sa.Column('nome_item', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('codigo_catmat_catser', sa.String(length=50), nullable=True),
    sa.Column('numero_sequencial_taxonomia', sa.String(length=4), nullable=False),
    sa.Column('codigo_identificacao_completo', sa.String(length=10), nullable=True),
    sa.Column('descricao_detalhada', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_subgrupo'], ['subgrupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_identificacao_completo')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_contrato', sa.Integer(), nullable=False),
    sa.Column('ano_contrato', sa.Integer(), nullable=False),
    sa.Column('id_processo_licitatorio', sa.Integer(), nullable=False),
    sa.Column('id_numero_modalidade', sa.Integer(), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('id_instrumento_contratual', sa.Integer(), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=False),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('data_fim_vigencia', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['id_instrumento_contratual'], ['instrumentocontratual.id'], ),
    sa.ForeignKeyConstraint(['id_numero_modalidade'], ['numeros_modalidade.id'], ),
    sa.ForeignKeyConstraint(['id_processo_licitatorio'], ['processos_licitatorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_filename', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_seguro', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=True),
    sa.Column('id_contrato', sa.Integer(), nullable=True),
    sa.Column('id_aocs', sa.Integer(), nullable=True),
    sa.Column('data_upload', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(id_contrato IS NOT NULL AND id_aocs IS NULL) OR (id_contrato IS NULL AND id_aocs IS NOT NULL)', name='check_origem_anexo'),
    sa.ForeignKeyConstraint(['id_aocs'], ['aocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_seguro')
    )
    op.create_table('itens_dfd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dfd_id', sa.Integer(), nullable=True),
    sa.Column('catalogo_item_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('valor_unitario_estimado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_total_estimado', sa.Numeric(precision=15, scale=2), sa.Computed('quantidade * valor_unitario_estimado', ), nullable=True),
    sa.Column('complemento_descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['catalogo_item_id'], ['catalogo_itens.id'], ),
    sa.ForeignKeyConstraint(['dfd_id'], ['dfds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_etp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etp_id', sa.Integer(), nullable=True),
    sa.Column('catalogo_item_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_total', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('valor_unitario_referencia', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['catalogo_item_id'], ['catalogo_itens.id'], ),
    sa.ForeignKeyConstraint(['etp_id'], ['etps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_contrato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('id_item_dfd', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('quantidade_contratada', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('valor_unitario_final', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_total_item', sa.Numeric(precision=15, scale=2), sa.Computed('quantidade_contratada * valor_unitario_final', ), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_item_dfd'], ['itens_dfd.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_aocs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aocs', sa.Integer(), nullable=False),
    sa.Column('id_item_contrato', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('saldo_anterior_snapshot', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('quantidade_entregue', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('status_item', sa.String(length=30), nullable=True),
    sa.CheckConstraint('quantidade_solicitada > 0', name='check_quantidade_solicitada_pos'),
    sa.ForeignKeyConstraint(['id_aocs'], ['aocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_item_contrato'], ['itens_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_aocs')
    op.drop_table('itens_contrato')
    op.drop_table('itens_etp')
    op.drop_table('itens_dfd')
    op.drop_table('anexos')
    op.drop_table('generation_logs')
    op.drop_table('contratos')
    op.drop_table('catalogo_itens')
    op.drop_table('trs')
    op.drop_table('templates')
    op.drop_table('subgrupos')
    op.drop_table('processos_licitatorios')
    op.drop_table('processos')
    op.drop_table('pedido')
    op.drop_table('logs_auditoria')
    op.drop_table('itens_risco')
    op.drop_table('dfd_equipe')
    op.drop_table('dfd_dotacoes')
    op.drop_table('ci_pagamentos')
    op.drop_table('usuarios')
    op.drop_table('numeros_modalidade')
    op.drop_table('matrizes_risco')
    op.drop_table('grupos')
    op.drop_table('etp_equipe')
    op.drop_table('etp_dotacoes')
    op.drop_index(op.f('ix_dfds_numero_protocolo_string'), table_name='dfds')
    op.drop_table('dfds')
    op.drop_table('aocs')
    op.drop_table('v_saldo_itens_contrato')
    op.drop_table('unidades_requisitantes')
    op.drop_table('tipos_documento')
    op.drop_table('perfis')
    op.drop_table('modalidade')
    op.drop_table('locais_entrega')
    op.drop_table('instrumentocontratual')
    op.drop_table('fornecedores')
    op.drop_table('etps')
    op.drop_table('dotacao')
    op.drop_table('descricao_item')
    op.drop_table('categorias')
    op.drop_table('agentes_responsaveis')
    # ### end Alembic commands ###
