"""Initial_tables

Revision ID: 620094dca58c
Revises: 
Create Date: 2025-12-15 14:56:04.415798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620094dca58c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentes_responsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_agentes_responsaveis_id'), 'agentes_responsaveis', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo_taxonomia', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_taxonomia'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('dotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('codigo_dotacao', sa.String(length=100), nullable=False),
    sa.Column('numero_ficha', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercicio', 'codigo_dotacao', name='uk_dotacao_exercicio_codigo')
    )
    op.create_index(op.f('ix_dotacao_id'), 'dotacao', ['id'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_table('instrumentos_contratuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_instrumentos_contratuais_id'), 'instrumentos_contratuais', ['id'], unique=False)
    op.create_table('locais_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_locais_entrega_id'), 'locais_entrega', ['id'], unique=False)
    op.create_table('modalidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('fundamentacao_legal', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_modalidade_id'), 'modalidade', ['id'], unique=False)
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_perfis_id'), 'perfis', ['id'], unique=False)
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_documento_id'), 'tipos_documento', ['id'], unique=False)
    op.create_table('unidades_requisitantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('codigo_administrativo', sa.String(length=20), nullable=True),
    sa.Column('id_unidade_pai', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade_pai'], ['unidades_requisitantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_unidades_requisitantes_id'), 'unidades_requisitantes', ['id'], unique=False)
    op.create_table('aocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_aocs', sa.String(length=100), nullable=False),
    sa.Column('ano_aocs', sa.Integer(), nullable=False),
    sa.Column('numero_pedido_externo', sa.String(length=50), nullable=True),
    sa.Column('data_emissao', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id_unidade_requisitante', sa.Integer(), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=True),
    sa.Column('id_agente_responsavel', sa.Integer(), nullable=True),
    sa.Column('id_local_entrega', sa.Integer(), nullable=True),
    sa.Column('id_dotacao', sa.Integer(), nullable=True),
    sa.Column('empenho', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_agente_responsavel'], ['agentes_responsaveis.id'], ),
    sa.ForeignKeyConstraint(['id_dotacao'], ['dotacao.id'], ),
    sa.ForeignKeyConstraint(['id_local_entrega'], ['locais_entrega.id'], ),
    sa.ForeignKeyConstraint(['id_solicitante'], ['agentes_responsaveis.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_requisitante'], ['unidades_requisitantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_aocs')
    )
    op.create_index(op.f('ix_aocs_id'), 'aocs', ['id'], unique=False)
    op.create_table('dfd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('descricao_sucinta', sa.String(length=255), nullable=False),
    sa.Column('justificativa_necessidade', sa.Text(), nullable=True),
    sa.Column('id_unidade_requisitante', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade_requisitante'], ['unidades_requisitantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', 'ano', name='uk_dfd_numero_ano')
    )
    op.create_index(op.f('ix_dfd_id'), 'dfd', ['id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_categoria', 'codigo', name='uk_grupo_codigo')
    )
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_table('numeros_modalidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_modalidade', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_modalidade'], ['modalidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_modalidade', 'numero', 'ano', name='uk_modalidade_numero_ano')
    )
    op.create_index(op.f('ix_numeros_modalidade_id'), 'numeros_modalidade', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('processos_licitatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dfd', sa.Integer(), nullable=False),
    sa.Column('numero_processo', sa.Integer(), nullable=False),
    sa.Column('ano_processo', sa.Integer(), nullable=False),
    sa.Column('id_modalidade', sa.Integer(), nullable=False),
    sa.Column('id_numero_modalidade', sa.Integer(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('valor_total_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_homologacao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_dfd'], ['dfd.id'], ),
    sa.ForeignKeyConstraint(['id_modalidade'], ['modalidade.id'], ),
    sa.ForeignKeyConstraint(['id_numero_modalidade'], ['numeros_modalidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_dfd'),
    sa.UniqueConstraint('numero_processo', 'ano_processo', name='uk_processo_adm')
    )
    op.create_index(op.f('ix_processos_licitatorios_id'), 'processos_licitatorios', ['id'], unique=False)
    op.create_table('subgrupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_grupo', 'codigo', name='uk_subgrupo_codigo')
    )
    op.create_index(op.f('ix_subgrupos_id'), 'subgrupos', ['id'], unique=False)
    op.create_table('catalogo_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_subgrupo', sa.Integer(), nullable=False),
    sa.Column('nome_item', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('codigo_catmat_catser', sa.String(length=50), nullable=True),
    sa.Column('numero_sequencial_taxonomia', sa.String(length=4), nullable=False),
    sa.Column('codigo_identificacao_completo', sa.String(length=10), nullable=True),
    sa.Column('descricao_detalhada', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("tipo IN ('Consumo', 'Permanente', 'Serviço')", name='check_tipo_item'),
    sa.ForeignKeyConstraint(['id_subgrupo'], ['subgrupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_identificacao_completo'),
    sa.UniqueConstraint('id_subgrupo', 'numero_sequencial_taxonomia', name='uk_item_sequencial')
    )
    op.create_index(op.f('ix_catalogo_itens_id'), 'catalogo_itens', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.Integer(), nullable=False),
    sa.Column('ano_contrato', sa.Integer(), nullable=False),
    sa.Column('id_processo_licitatorio', sa.Integer(), nullable=False),
    sa.Column('id_numero_modalidade', sa.Integer(), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('id_instrumento_contratual', sa.Integer(), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=False),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('data_fim_vigencia', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('data_fim_vigencia >= data_inicio_vigencia', name='check_vigencia'),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['id_instrumento_contratual'], ['instrumentos_contratuais.id'], ),
    sa.ForeignKeyConstraint(['id_numero_modalidade'], ['numeros_modalidade.id'], ),
    sa.ForeignKeyConstraint(['id_processo_licitatorio'], ['processos_licitatorios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_contrato', 'ano_contrato', name='uk_contrato_full')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_seguro', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=True),
    sa.Column('id_contrato', sa.Integer(), nullable=True),
    sa.Column('id_aocs', sa.Integer(), nullable=True),
    sa.Column('data_upload', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('(id_contrato IS NOT NULL AND id_aocs IS NULL) OR (id_contrato IS NULL AND id_aocs IS NOT NULL)', name='check_origem_anexo'),
    sa.ForeignKeyConstraint(['id_aocs'], ['aocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_seguro')
    )
    op.create_index(op.f('ix_anexos_id'), 'anexos', ['id'], unique=False)
    op.create_table('itens_dfd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dfd', sa.Integer(), nullable=False),
    sa.Column('id_catalogo_item', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('valor_unitario_estimado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_catalogo_item'], ['catalogo_itens.id'], ),
    sa.ForeignKeyConstraint(['id_dfd'], ['dfd.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_dfd', 'id_catalogo_item', name='uk_item_dfd')
    )
    op.create_index(op.f('ix_itens_dfd_id'), 'itens_dfd', ['id'], unique=False)
    op.create_table('itens_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('id_item_dfd', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('quantidade_contratada', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('valor_unitario_final', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_item_dfd'], ['itens_dfd.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_contrato', 'id_item_dfd', name='uk_item_origem_duplicada'),
    sa.UniqueConstraint('id_contrato', 'numero_item', name='uk_item_numero_contrato')
    )
    op.create_index(op.f('ix_itens_contrato_id'), 'itens_contrato', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_contrato_id'), table_name='itens_contrato')
    op.drop_table('itens_contrato')
    op.drop_index(op.f('ix_itens_dfd_id'), table_name='itens_dfd')
    op.drop_table('itens_dfd')
    op.drop_index(op.f('ix_anexos_id'), table_name='anexos')
    op.drop_table('anexos')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_catalogo_itens_id'), table_name='catalogo_itens')
    op.drop_table('catalogo_itens')
    op.drop_index(op.f('ix_subgrupos_id'), table_name='subgrupos')
    op.drop_table('subgrupos')
    op.drop_index(op.f('ix_processos_licitatorios_id'), table_name='processos_licitatorios')
    op.drop_table('processos_licitatorios')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_numeros_modalidade_id'), table_name='numeros_modalidade')
    op.drop_table('numeros_modalidade')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_dfd_id'), table_name='dfd')
    op.drop_table('dfd')
    op.drop_index(op.f('ix_aocs_id'), table_name='aocs')
    op.drop_table('aocs')
    op.drop_index(op.f('ix_unidades_requisitantes_id'), table_name='unidades_requisitantes')
    op.drop_table('unidades_requisitantes')
    op.drop_index(op.f('ix_tipos_documento_id'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index(op.f('ix_perfis_id'), table_name='perfis')
    op.drop_table('perfis')
    op.drop_index(op.f('ix_modalidade_id'), table_name='modalidade')
    op.drop_table('modalidade')
    op.drop_index(op.f('ix_locais_entrega_id'), table_name='locais_entrega')
    op.drop_table('locais_entrega')
    op.drop_index(op.f('ix_instrumentos_contratuais_id'), table_name='instrumentos_contratuais')
    op.drop_table('instrumentos_contratuais')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_dotacao_id'), table_name='dotacao')
    op.drop_table('dotacao')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_agentes_responsaveis_id'), table_name='agentes_responsaveis')
    op.drop_table('agentes_responsaveis')
    # ### end Alembic commands ###
