"""ajustes_models_para_testes

Revision ID: ffca60680fa2
Revises: 324edd6a9c4c
Create Date: 2025-12-15 22:02:16.694937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffca60680fa2'
down_revision: Union[str, Sequence[str], None] = '324edd6a9c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('objeto', sa.String(length=255), nullable=True))
    op.add_column('dfds', sa.Column('etp_id', sa.Integer(), nullable=True))
    op.add_column('dfds', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'dfds', 'etps', ['etp_id'], ['id'])
    op.alter_column('usuarios', 'id_perfil',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'id_perfil',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'dfds', type_='foreignkey')
    op.drop_column('dfds', 'is_active')
    op.drop_column('dfds', 'etp_id')
    op.drop_column('contratos', 'objeto')
    # ### end Alembic commands ###
